Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |subconfig|
    subconfig.vm.box = "ubuntu/bionic64"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8080
    subconfig.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL
    
  end

  config.vm.define "centos" do |subconfig|
    subconfig.vm.box = "centos/7"
  end
  
end
